document.getElementById("product1Img").src = product1.imgSrc ;
document.getElementById("product1Name").innerHTML = product1.name ;
document.getElementById("product1Price").innerHTML= product1.price ;
document.getElementById("product1Description").innerHTML= product1.description;
document.getElementById("product1Nutrition").innerHTML = product1.calorie;
document.getElementById("product1ProductName").innerHTML = product1.subProduct1.name
document.getElementById("product1ProductPrice").innerHTML = product1.subProduct1.price
document.getElementById("product2ProductName").innerHTML = product1.subProduct2.name
document.getElementById("product2ProductPrice").innerHTML = product1.subProduct2.price
document.getElementById("product3ProductName").innerHTML = product1.subProduct3.name
document.getElementById("product3ProductPrice").innerHTML = product1.subProduct3.price
document.getElementById("product4ProductName").innerHTML = product1.subProduct4.name
document.getElementById("product4ProductPrice").innerHTML = product1.subProduct4.price
document.getElementById("product5ProductName").innerHTML = product1.subProduct5.name
document.getElementById("product5ProductPrice").innerHTML = product1.subProduct5.price
document.getElementById("product6ProductName").innerHTML = product1.subProduct6.name
document.getElementById("product6ProductPrice").innerHTML = product1.subProduct6.price
document.getElementById("product7ProductName").innerHTML = product1.subProduct7.name
document.getElementById("product7ProductPrice").innerHTML = product1.subProduct7.price
document.getElementById("product8ProductName").innerHTML = product1.subProduct8.name
document.getElementById("product8ProductPrice").innerHTML = product1.subProduct8.price
document.getElementById("product9ProductName").innerHTML = product1.subProduct9.name
document.getElementById("product9ProductPrice").innerHTML = product1.subProduct9.price
document.getElementById("product10ProductName").innerHTML = product1.subProduct10.name
document.getElementById("product10ProductPrice").innerHTML = product1.subProduct10.price
document.getElementById("product11ProductName").innerHTML = product1.subProduct11.name
document.getElementById("product11ProductPrice").innerHTML = product1.subProduct11.price
document.getElementById("product12ProductName").innerHTML = product1.subProduct12.name
document.getElementById("product12ProductPrice").innerHTML = product1.subProduct12.price